---
- name: pre tesk add_hosts
  hosts: localhost
  connection: local
  serial: 1
  gather_facts: no

  pre_tasks:
    - include_tasks: ./roles/hosts_autopass/tasks/add_hosts.yml

- name: Install host_autopass on the local
  hosts: all
  connection: local
  serial: 1
  gather_facts: no

  roles:
    - { role: ./roles/hosts_autopass, tags: ['local'] }

- name: Install host_autopass on the all
  hosts: all
  serial: 1
  gather_facts: no
  become: yes

  roles:
    - { role: ./roles/hosts_autopass, tags: ['workers'] }
