  
  - name: Add "/etc/hosts"
    blockinfile: 
      dest: /etc/hosts
      content: "{{ lookup('template', '~/ansible-roles/roles/hosts_autopass/templates/hosts.j2') }}"
      state: present
    become: yes    
    tags: local

  - name: Add "/etc/ansible/hosts"
    blockinfile: 
      create: yes
      dest: /etc/ansible/hosts
      content: "{{ lookup('template', '~/ansible-roles/roles/hosts_autopass/templates/ansible-hosts.j2') }}"
      state: present
    become: yes
    tags: local   
