  
  - name: ssh-keygen ansible-server
    connection: local                 
    command: "ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ''"
    ignore_errors: yes
    run_once: true                   
    tags: local,all

  - name: import id_rsa.pub
    connection: local
    command: "cat ~/.ssh/id_rsa.pub"
    register: id_pub
    run_once: true
    tags: local,all

  - name: add ansible-node authrized keys
    lineinfile:
      dest: ~/.ssh/authorized_keys
      line: "{{ id_pub.stdout }}"
    tags: local,all
      

