  
  - name: ssh-keygen ansible-server
    command: "ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ''"
    ignore_errors: yes
    run_once: true                   
    tags: local_all

  - name: import id_rsa.pub
    command: "cat ~/.ssh/id_rsa.pub"
    register: id_pub
    run_once: true
    tags: local_all

  - name: add ansible-node authrized keys
    lineinfile:
      dest: ~/.ssh/authorized_keys
      line: "{{ id_pub.stdout }}"
    tags: local_all
      

