---
  - include_tasks:
      file: add_known_hosts.yml
      apply:
        tags:
          - master

  - include_tasks: 
      file: add_authorized_keys.yml
      apply:
        tags: 
          - master

  - include_tasks: 
      file: add_all_host.yml
      apply:
        tags: 
          - workers
