---

#  - include_tasks: add_hosts.yml

  - include_tasks: add_known_hosts.yml
    tags: local    

  - include_tasks: add_authorized_keys.yml
    tags: local

  - include_tasks: add_all_host.yml
    tags: workers
