---
- name: Install host_autopass on the localhost
  hosts: localhost
  connection: local
  serial: 1
  gather_facts: no
  become: yes
  become_method: sudo

  roles:
    - { role: ./roles/hosts_autopass, tags: [local] }


